#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm test
# npx lint-staged
# npm run lint-staged-node
# yarn lint-staged-cli
yarn lint-staged-node
# yarn commit
# yarn cz
# git cz
# yarn commitmsg
yarn changelog
